### ISSUE TITLE
FR: Поиск блоков

### ISSUE THREAD

**Issue by rusich** [pandrew83/FXGraph#1]
Очень утомительно, с непривычки, искать блоки (очень длинный список)
Было бы неплохо реализовать поиск в панели "Блоки", такой, чтобы по мере ввода текста список блоков фильтровался согласно ввода.
Что-то на подобии этого:
![image](https://user-images.githubusercontent.com/11703180/59486488-64ecaa80-8eb4-11e9-9bd7-cd3fd151402b.png)

**Comment by pandrew83** [comment]
Вчера Кирилл это же предложил...
Попробуй ты это реализовать. Я подскажу как это реализуется. За это время в MFC немного разобрался.

**Comment by rusich** [comment]
Хорошо, с понедельника займусь.

пт, 14 июн. 2019 г., 22:36 pandrew83 <notifications@github.com>:

**Comment by pandrew83** [comment]
Solved
