### ISSUE TITLE
Удаление элементов на схеме

### ISSUE THREAD

**Issue by rusich** [pandrew83/FXGraph#2]
Нужно обязательно реализовать удаление выделенных элементов с клавиатуры, клавишей Delete - действие интуитивно напрашивается.

**Comment by pandrew83** [comment]
Да у меня это мысль тоже была, но я её пока отложил из-за того, что не придумал, а какие еще кнопки нужно реализовать.
Хотелось, все за один раз реализовать.

**Comment by pandrew83** [comment]
Реализовано
